name: A Hacker's Evolution
layout_spectrum: 0.010433274321258068
typography_spectrum: 0.9450721114408225
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5853871528524905
  lightness: 0.5338418332394212
  saturation: 0.09314107848331332
  rhythmicContrast: 0.4547302210703492
title: ''
author:
  name: Amr Ali
  url: 'https://amrali.me'
  email: me@amrali.me
content_rating:
  adult: false
